### ISSUE TITLE
Decorator for aliasing the last value

### ISSUE THREAD

**Issue by alexlafroscia** [machty/ember-concurrency-decorators#12]
I find myself using this pattern a lot in my code:

```javascript
class Foo
  @task
  someTask = function*() { /* whatever */ };

  @alias('someTask.lastSuccessful.value')
  someTaskValue;
}
```

I came up with a little helper that just removes the need to add the `lastSuccessful.value` bit to the end, and allows an option for providing a default value. Would you be interested in adding the helper to this project? Or do you want to keep the decorators to just task definition?

**Comment by buschtoens** [comment]
I find myself doing this a lot to!

What would your proposed API look like?

**Comment by alexlafroscia** [comment]
The simply little decorator I made looks like this:

```javascript
class Foo
  @task
  someTask = function*() { /* whatever */ };

  @lastValue('someTask')
  someTaskValue;
}
```

You can also provide a default value, if the task returned something that `isNone` or hasn't been run yet. I found this useful when passing a task's value into something validated with `@ember-decorators/argument` that is expecting an array, that I didn't want to make optional

```javascript
class Foo
  @task
  someTask = function*() { /* whatever */ };

  @lastValue('someTask', { default: 'foo' })
  someTaskValue;
}
```

Or, in cases like returning a non-primitive where you don't want to potentially leak the same object that could be mutated, you can provide a factory function for creating the default (which supersedes the `default` if both happened to be provided:

```javascript
class Foo
  @task
  someTask = function*() { /* whatever */ };

  @lastValue('someTask', { defaultFactory: () => ({}) })
  someTaskValue;
}
```
