### ISSUE TITLE
Test waiter decorator

### ISSUE THREAD

**Issue by willviles** [machty/ember-concurrency-decorators#17]
Whilst upgrading an app to ES6 classes, I noticed [ember-concurrency-test-waiter](https://github.com/bendemboski/ember-concurrency-test-waiter) is being used as a task modifier on some of the tasks. Tests fail without them.

Assuming this is a recommended way to implement test waiters for ember-concurrency tasks, could a decorator be a good solution?

**Before**
```js
export default EmberObject.extend({
  fooTask: withTestWaiter(task(function*() {
    // task logic...
  }))
});
```

or

```js
export default EmberObject.extend({
  fooTask: task(function*() {
    // task logic...
  }).testWaiter()
});
```

**After**
```js
import { dropTask, testWaiter } from 'ember-concurrency-decorators'
class Foo {
  @dropTask
  @testWaiter
  *fooTask () {
    // task logic...
  }
}
```

I'm not sure that this is the best place to implement, or whether a decorator is best left in the scope of the [ember-concurrency-test-waiter](https://github.com/bendemboski/ember-concurrency-test-waiter) addon.

Also does anybody know the reason why test waiters were packaged as a further addon and not implemented in ember-concurrency?

**Comment by buschtoens** [comment]
To make it work _now_ you could do this:

```js
// app.js
import defineModifier from 'ember-concurrency-test-waiter/define-modifier';

defineModifier();
```
```js
import { dropTask } from 'ember-concurrency-decorators'
class Foo {
  @dropTask({ withTestWaiter: true })
  *fooTask () {
    // task logic...
  }
}
```

**Comment by buschtoens** [comment]
If we make this a decorator, the order they are called in has to be inverted, so ...

```js
import { dropTask, testWaiter } from 'ember-concurrency-decorators';

class Foo {
  @testWaiter
  @dropTask
  *fooTask () {
    // task logic...
  }
}
```


... instead of `@dropTask @testWaiter`. We probably _could_ still make the latter work by lazily evaluating or adding some special handling to the proposed `@testWaiter` decorator, but I don't think that's worth the hassle.

This is similar to how you have to call

```js
@className
@computed('isAngry')
get isRed() {
  return this.isAngry;
}
```

instead of


```js
@computed('isAngry')
@className
get isRed() {
  return this.isAngry;
}
```

**Comment by buschtoens** [comment]
@willviles Is https://github.com/machty/ember-concurrency-decorators/issues/17#issuecomment-428228635 a valid solution for you or do you require an additional decorator?

**Comment by willviles** [comment]
I think https://github.com/machty/ember-concurrency-decorators/issues/17#issuecomment-428228635 is a good solution. Happy to close this issue!

**Comment by buschtoens** [comment]
Cool, thanks for following up! 😊
