### ISSUE TITLE
Parse error using JS native class and decorators

### ISSUE THREAD

**Issue by sly7-7** [machty/ember-concurrency-decorators#40]
I encounter a parse error, when declaring something like in a JS native class, even if the transpilation is ok, and the project build correctly.

```
 @keepLatestTask
  *resizeWidth() {
    yield waitForQueue('afterRender');
    this.onResize();
  }
``` 
Parsing error: Unexpected token '{'

I use `"babel-eslint": "^8.2.6"`, `"@ember-decorators/babel-transforms": "^3.1.5"`, `"ember-cli-babel": "^7.1.2",`

**Comment by buschtoens** [comment]
The actual app build succeeds, right? So this is a problem with eslint.

You are using an outdated version of `babel-eslint`. Please try upgrading to the latest version. I know that Babel 6 did not support decorating generator methods.

**Comment by sly7-7** [comment]
Thanks @buschtoens. Actually upgrading to the latest babel-eslint does not work either, but the assignment syntax works "perfectly", I will stick on it for now.
