### ISSUE TITLE
Error: Attempting to lookup an injected property on an object without a container

### ISSUE THREAD

**Issue by allthesignals** [machty/ember-concurrency-decorators#55]
code:
```

  @task
  findRecordTask = function* () {
    return yield this.store.findRecord(this.modelName, this.modelId);
  }

  didReceiveAttrs() {
    this.findRecordTask.perform();
  }
```

error:
```
Error: Assertion Failed: Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container.
```

![image](https://user-images.githubusercontent.com/5004319/60278732-f6edad80-98cd-11e9-8552-0c7fff13a77e.png)

**Comment by buschtoens** [comment]
What version on Ember, `ember-cli-babel`, `ember-concurrency-decorators` are you using?

Are you using this on an addon? How is the class instantiated?

**Comment by buschtoens** [comment]
Can you please provide the full class source code?

**Comment by allthesignals** [comment]
Hi @buschtoens - it looks like you updated the README and added some very thorough instructions: https://github.com/machty/ember-concurrency-decorators#stage-1-decorators

This is what fixed my issue. Thank you.

FWIW:

"ember-concurrency-decorators": "1.0.0-beta.4",
"ember-cli-babel": "^7.7.3",

>Are you using this on a component?

Yes

How is the class instantiated?

using `.perform` on `didReceiveAttrs` hook.

```javascript
class LayerDataProviderComponent extends Component {
  init(...args) {
    super.init(...args);

    this.findRecordTask.perform();
  }

  @service
  store;

  modelId = null;

  modelName = 'carto-data-provider';

  @task
  findRecordTask = function* () {
    return yield this.store.findRecord(this.modelName, this.modelId);
  }

  didReceiveAttrs() {
    this.findRecordTask.perform();
  }
}
```

**Comment by buschtoens** [comment]
Great to hear! Can we close this then? :)

**Comment by allthesignals** [comment]
Please!
