### ISSUE TITLE
Task groups don't work with glimmer components

### ISSUE THREAD

**Issue by jrjohnson** [machty/ember-concurrency-decorators#57]
I don't know if this belongs here or in the `ember-concurrency` repo.

Using a taskGroup with a glimmer component throws `obj.get is not a function`. Comes from [here](https://github.com/machty/ember-concurrency/blob/master/addon/-property-modifiers-mixin.js#L78) where EmberObject expects `get` to exist.

```
import Component from '@glimmer/component';
import { task, taskGroup } from 'ember-concurrency-decorators';

export default class SimpleChart extends Component {
  @taskGroup
  someGroup;
  @task({ group: 'someGroup' })
  *doSomething() {

  }
}
```

**Comment by buschtoens** [comment]
Fixed via https://github.com/machty/ember-concurrency/pull/321.

Thanks @jrjohnson!
