### ISSUE TITLE
Short form of generator functions in README makes prettier unhappy

### ISSUE THREAD

**Issue by kategengler** [machty/ember-concurrency-decorators#58]
The short form demonstrated in the README:

```
@task
*doStuff() {
  // ...
}
```

Makes prettier complain: ```SyntaxError: Unexpected token```

This form **works**, but only makes prettier unhappy.

The following form works with prettier:

```
@task
doStuff = function*() {
  // ...
}
```

This issue is just to document the problem for others (or maybe future me)

**Comment by buschtoens** [comment]
Can you check, whether you are on the latest Prettier version?
It's working fine in the [Prettier Playgroud](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UAAjFgNY4BUAJhAMowCuAZhwBQCUxZHDgD0wnADpJZAL5kylGmUYt2XPgKhDREqVFlR5VTNW7AcAJziYq5qgCNUcJDhjm2cHNP7LWnHv1JNETFJcRk5CiMTM0trdFt0BycXNw8vJSZfNQDBYJ0wvRkQABoQCAAHGABLaExkUHjzCAB3AAV4hDqUdAA3CCqGEpA7c3QwajgYZnKxqqgAc2RXd1KACxgAW1QAdVWq+EwZsDhmTv2qnv2AT2RwbCG5zDhbVtH5jfRkDnRUJ9KAK0wAA8AEKjcaTZjoDZwAAyczgXx+fxAgKBzDm80cAEU2BB4EjfnBSjNzE9zLc7IkrqhoENyuY5jBtgMYKtkAAOAAMJKaT22o3KtwZVmePURpQAjnj4K8Kl0QFgALRQOBwBjqoaWaVVSyvdDvT5Ib5E0pPDZVJapM2YnEyxHG5HEkD2FkMNnIABMpVc6CqqExAGEIBsPrcoNAJSA2E8ACqJLomp7SaRAA).

**Comment by kategengler** [comment]
prettier `1.18.2`

**Comment by buschtoens** [comment]
Hm. Are you using prettier through `eslint` or directly? What's your prettier config?

**Comment by buschtoens** [comment]
AFAICT prettier doesn't directly depend on `@babel/parser`, but relies on the project to supply the proper version. I know that the short form is only supported since `@babel/core@^7.5.0`, so I guess you need the same minimum version of `@babel/parser`.

What does `yarn list --pattern @babel/parser` turn up?

(In case you are using the Babel parser for prettier that is 😅 )

**Comment by kategengler** [comment]
I used it both directly and through eslint, to the same result. `@babel/parser@7.6.4`

I have narrowed down what is causing the problem, as shown in the prettier playground [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABMAbAhgZxwSzAB0o4APABwgCcYACAEzgDMsBXDezXHOgZRhtmzOsBJ06qGLgDW4ugCoGEAUOYAKAJSj5dAPR6cg4fIC+AbhKmSIADQgIFGPmg5koLNWoQA7gAVPBDcULAwfLABPN3sAI2osMBk4GD4KBPwoAHNkGGo2OHsACxgAWwwAdUL8eBw0sDg+IOr8ADdqiORwPDsQDJw4Wj94zJKsZFYMfvsAKxwyACF4xOS+LBK4ABkMuHHQqZBZsj4MzIw4AEU2CHhdyYKQNOp+6k6YrBi4DB6KagyYcvwDBghWQAA4AAz2H4QfrleIUTo-ODPFo7ewARyu8CGjmCIFwAFpSHAmAwetQ4Jj8BShlgRmMkBN9v0Svgcnl7gQsmdLtcdkhcvl7NIYgCgSCkAAmYXxfAYE4AYQgJVGnVCX3sbH6ABV3sEmXBTKYgA), it does not like the short hand syntax when the class has a decorator before the export.

It's not an issue with this addon, for sure, but this issue can serve as a heads up. Thanks for your help @buschtoens

**Comment by buschtoens** [comment]
Awesome! Thanks for following up on this!

Thanks to your explanation I was able to trace it back to the cause: [`parser-babylon.js#L64-L71`](https://github.com/prettier/prettier/blob/473bacf966af5511934957d6a43dc3a5c0287caf/src/language-js/parser-babylon.js#L64-L71) only allows `decoratorsBeforeExport: false`.

As you can see in this [Prettier Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBsYAdKAATEtIGcWBLMOp1lvAZRjlixPMDp489GKwDWEvACoCEQcOIAKAJRiFeAPT6WQkQoC+Abjpm6IADQgIGGO2gtkoUtmwQA7gAUvBHcUUkpfUgBPdwcAI2xSMFk4GH4MRPYoAHNkGGxyOAcACxgAW0oAdSL2eBZ0sDh+YJr2ADcayORwNnsQTJY4XH8ErNLSZDJKAYcAKxY0ACEEpJT+UlK4ABlMuAmw6ZA5tH5MrMo4AEVyCHg9qcKQdOwB7C7Y0li4Sl6MbEyYCrsAgwIrIAAcAAYHL8IAMKgkMF1fnAXq1dg4AI7XeDDJwhECsAC0UDgcCIBF62DgWPYVOGpFG4yQkwOA1K7Fy+QeHGy5yuN12SDyBQcMligOBoKQACZRQl2JRTgBhCClMZdMLfBzkAYAFQ+IRZcDMZiAA), it works, when you change the order.
