### ISSUE TITLE
Question: Is there way to use EC tasks lifecycle events within EC decorators?

### ISSUE THREAD

**Issue by KalachevDev** [machty/ember-concurrency-decorators#60]
The title actually describes my issue pretty well, what is the valid syntax for using modifiers?

Like:
```javascript
someTask: task(function * () {
     yield stuff();
}).on('didInsertElement')
```

**Comment by buschtoens** [comment]
Can you try this?

```ts
class {
  @task({ on: 'didInsertElement' })
  *someTask() {
    // ...
  }
}
```

**Comment by KalachevDev** [comment]
@buschtoens it works, thank you! It might be good to declare it in docs somehow, or did I miss something and it is already there? :)

**Comment by buschtoens** [comment]
Yes, you're right. It's not explicitly documented. In fact _all_ modifiers "just work" even third-party ones, like [`ember-concurrency-test-waiter`](https://github.com/bendemboski/ember-concurrency-test-waiter).
